# docker-compose.yml (Compose V2 : le champ "version" est inutile, on l'omet)
services:
  iotBadgeDoorSimulateor:
    build: ./iotsimulator
    container_name: iotBadgeDoorSimulateor
    image: badgeusedoor/iotbadgedoorsimulator
    environment:
      MQTT_HOST: "172.31.253.71"
      MQTT_PORT: "1883"
      MQTT_USER: "toto"
      MQTT_PASS: "toto"
      SIMULATOR_DATA_DIR: "/data"
    ports:
      - "9002:9002"
    networks: [iot]
    volumes:
      - ./iotsimulator/simulator_data:/data
    restart: unless-stopped
  bridge:
    build: ./bridge
    container_name: bridge
    environment:
      MQTT_HOST: "172.31.253.71"
      MQTT_PORT: "1883"
      MQTT_USER: "toto"
      MQTT_PASS: "toto"
      BADGE_EVENTS_TOPIC: "iot/badgeuse/+/events"
      DOOR_CMDS_FMT: "iot/porte/{door_id}/events"
      OPEN_ACTION: "open"
      AUTO_CLOSE_SEC: "5"  
      DEBOUNCE_SEC: "2"
    networks: [iot]
    restart: unless-stopped
    ports:
      - "9010:9010"

  entrance-cockpit-backend:
    build: ./EntranceCockpitBackend
    container_name: entrance-cockpit-backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://172.31.252.35:5432/coredb}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-coreuser}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-episen_tp_paas}
      EVENTS_KAFKA_ENABLED: ${EVENTS_KAFKA_ENABLED:-true}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-172.31.252.16:9092}
      KAFKA_TOPIC: ${KAFKA_TOPIC:-entrance}
      KAFKA_TOPIC_ATTEMPTS: ${KAFKA_TOPIC_ATTEMPTS:-attempts}
      EVENTS_KAFKA_EXTRA_TOPICS: ${EVENTS_KAFKA_EXTRA_TOPICS:-logs}
    ports:
      - "9500:9500"
    depends_on:
      - iotBadgeDoorSimulateor
    networks: [iot]
    restart: unless-stopped

  entrance-cockpit-front:
    build: ./EntranceCockpitFront
    container_name: entrance-cockpit-front
    ports:
      - "4201:80"
    networks: [iot]
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped

    environment:
      MQTT_USER: "toto"
      MQTT_PASSWORD: "toto"

    ports:
      - "1883:1883"
      - "9001:9001"

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks: [iot]
  hivemq:
    image: hivemq/hivemq-ce:latest
    container_name: hivemq
    ports:
      - "8080:8080"   # Web UI
      - "1884:1883"   # MQTT port (alternative)
    volumes:
      - ./hivemq/data:/opt/hivemq/data
      - ./hivemq/log:/opt/hivemq/log
    restart: unless-stopped

 
 
networks:
  iot: {}


