services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    environment:
      MQTT_USER: toto
      MQTT_PASSWORD: toto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
