services:
  entrance-cockpit-front:
    build: ./EntranceCockpitFront
    container_name: entrance-cockpit-front
    ports:
      - "4201:80"
    networks: [iot]
    restart: unless-stopped

networks:
  iot: {}
